#!/usr/bin/env bash
# Generate the package-manager manifests and the updater's release feed from a
# finished release directory.
#
#   Formula/pcsync.rb   a Homebrew tap formula (macOS and Linux, both arches)
#   bucket/pcsync.json  a Scoop manifest (Windows amd64)
#   update-feed.json    what `pcsync update` reads
#
# Every version and every checksum comes from the release's own SHA256SUMS. That
# is the point: a hand-written formula is a hash somebody typed, and a hash
# somebody typed is a hash that will eventually be wrong. Here the same file the
# cosign signature covers is the source for all three manifests, so a manifest
# can never disagree with the release it describes.
#
# Usage:
#   scripts/release/generate-manifests.sh <dist-dir> <version> <base-url> <out-dir>
#
#   version   the release tag, e.g. v1.3.0
#   base-url  where the artifacts are downloadable from, e.g.
#             https://github.com/OWNER/REPO/releases/download/v1.3.0
set -euo pipefail

dist="${1:?usage: generate-manifests.sh <dist-dir> <version> <base-url> <out-dir>}"
version="${2:?missing version}"
baseurl="${3:?missing base URL}"
out="${4:?missing out dir}"

sums="$dist/SHA256SUMS"
[ -f "$sums" ] || { echo "generate-manifests: $sums not found" >&2; exit 1; }

bare="${version#v}" # Homebrew and Scoop versions start with a digit

# digest <artifact> — the recorded SHA-256 of one artifact, or empty if the
# release does not publish it. An absent artifact is not fatal: a release that
# skipped, say, the Windows target should still produce a Homebrew formula.
digest() {
  awk -v want="$1" '{ name = $2; sub(/^\*/, "", name); sub(/^\.\//, "", name);
                      if (name == want) { print $1; exit } }' "$sums"
}

require() {
  local d
  d="$(digest "$1")"
  if [ -z "$d" ]; then
    echo "generate-manifests: $1 is not in SHA256SUMS" >&2
    return 1
  fi
  printf '%s' "$d"
}

mkdir -p "$out/Formula" "$out/bucket"

# --- Homebrew tap -------------------------------------------------------------
#
# The formula installs the prebuilt binary rather than building from source. That
# is the honest thing for this project: the binary Homebrew would build is the
# same pure-Go static binary the release already produced and signed, and asking
# every user's machine to rebuild it only adds a way for the two to differ.
darwin_arm="$(require pcsync-darwin-arm64)"
darwin_amd="$(require pcsync-darwin-amd64)"
linux_arm="$(digest pcsync-linux-arm64)"
linux_amd="$(digest pcsync-linux-amd64)"

{
  cat <<RUBY
# Generated by scripts/release/generate-manifests.sh for $version — do not edit.
# Every sha256 below is copied from the release's SHA256SUMS, which is the file
# the cosign signature covers.
class Pcsync < Formula
  desc "Private Cloud sync client — keeps one local folder in step with your server"
  homepage "https://github.com/guru-bharadwaj20/private-cloud"
  version "$bare"
  license "AGPL-3.0-or-later"

  on_macos do
    on_arm do
      url "$baseurl/pcsync-darwin-arm64"
      sha256 "$darwin_arm"
    end
    on_intel do
      url "$baseurl/pcsync-darwin-amd64"
      sha256 "$darwin_amd"
    end
  end
RUBY
  if [ -n "$linux_arm" ] && [ -n "$linux_amd" ]; then
    cat <<RUBY

  on_linux do
    on_arm do
      url "$baseurl/pcsync-linux-arm64"
      sha256 "$linux_arm"
    end
    on_intel do
      url "$baseurl/pcsync-linux-amd64"
      sha256 "$linux_amd"
    end
  end
RUBY
  fi
  cat <<'RUBY'

  def install
    bin.install Dir["pcsync-*"].first => "pcsync"
  end

  def caveats
    <<~EOS
      pcsync is configured by a file, not by flags. Start from the template:
        mkdir -p ~/.config/pcsync
        curl -fsSLo ~/.config/pcsync/config.json \
          https://raw.githubusercontent.com/guru-bharadwaj20/private-cloud/main/client/config.example.json
      Then check it before you rely on it:
        pcsync doctor -config ~/.config/pcsync/config.json
    EOS
  end

  test do
    assert_match "pcsync", shell_output("#{bin}/pcsync version")
  end
end
RUBY
} > "$out/Formula/pcsync.rb"

# --- Scoop bucket -------------------------------------------------------------
#
# Scoop verifies the hash before it puts anything on PATH, so the manifest is a
# real check and not a convenience. The #/pcsync.exe fragment renames the
# downloaded artifact, which is how a versioned filename becomes a command.
windows_amd="$(require pcsync-windows-amd64.exe)"
cat > "$out/bucket/pcsync.json" <<JSON
{
    "version": "$bare",
    "description": "Private Cloud sync client — keeps one local folder in step with your server",
    "homepage": "https://github.com/guru-bharadwaj20/private-cloud",
    "license": "AGPL-3.0-or-later",
    "architecture": {
        "64bit": {
            "url": "$baseurl/pcsync-windows-amd64.exe#/pcsync.exe",
            "hash": "$windows_amd"
        }
    },
    "bin": "pcsync.exe",
    "checkver": {
        "github": "https://github.com/guru-bharadwaj20/private-cloud"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/guru-bharadwaj20/private-cloud/releases/download/v\$version/pcsync-windows-amd64.exe#/pcsync.exe"
            }
        },
        "hash": {
            "url": "https://github.com/guru-bharadwaj20/private-cloud/releases/download/v\$version/SHA256SUMS"
        }
    }
}
JSON

# --- the updater's feed -------------------------------------------------------
#
# The feed is a pointer, not a promise: it says which version exists and where
# the files are. pcsync trusts none of it — it fetches SHA256SUMS, verifies the
# cosign signature over that file, and only then believes a digest. So this file
# needs no signature of its own, and gets none, rather than one that would look
# reassuring without being checked.
cat > "$out/update-feed.json" <<JSON
{
  "version": "$version",
  "released_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "notes_url": "https://github.com/guru-bharadwaj20/private-cloud/releases/tag/$version",
  "base_url": "$baseurl/",
  "checksums_url": "$baseurl/SHA256SUMS",
  "signature_url": "$baseurl/SHA256SUMS.sig",
  "certificate_url": "$baseurl/SHA256SUMS.pem"
}
JSON

echo "generate-manifests: wrote"
echo "  $out/Formula/pcsync.rb"
echo "  $out/bucket/pcsync.json"
echo "  $out/update-feed.json"
