package auth

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"github.com/go-webauthn/webauthn/protocol"
	"github.com/go-webauthn/webauthn/webauthn"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Store is the persistence layer for identity.
//
// Queries are hand-written rather than generated. The design doc named sqlc,
// and that is still the right call once the query count grows — but adding a
// code-generation step to the build for the ~20 queries here would cost more
// than it saves. Revisit when files and sharing land in slice 3.
type Store struct {
	pool *pgxpool.Pool
}

func NewStore(pool *pgxpool.Pool) *Store { return &Store{pool: pool} }

// uniqueViolation reports whether err is a Postgres unique-constraint error,
// so callers can turn a race into a clean "already taken" instead of a 500.
func uniqueViolation(err error) bool {
	var pgErr *pgconn.PgError
	return errors.As(err, &pgErr) && pgErr.Code == "23505"
}

// --- users ------------------------------------------------------------------

func (s *Store) CountUsers(ctx context.Context) (int, error) {
	var n int
	err := s.pool.QueryRow(ctx, `SELECT count(*) FROM users`).Scan(&n)
	return n, err
}

// CreateUser inserts a user with a CALLER-SUPPLIED id.
//
// The id is not generated by the database on purpose. During bootstrap
// registration the UUID is minted before the row exists, because it is handed
// to the authenticator as the WebAuthn user handle and baked into the
// credential. If Postgres generated a different id here, the stored user and
// the handle inside the passkey would disagree — and since FinishLogin
// validates the user handle, the freshly created admin could never sign in.
func (s *Store) CreateUser(ctx context.Context, id uuid.UUID, username, displayName string, isAdmin bool) (*User, error) {
	u := &User{}
	err := s.pool.QueryRow(ctx, `
		INSERT INTO users (id, username, username_fold, display_name, is_admin)
		VALUES ($1, $2, lower($2), $3, $4)
		RETURNING id, username, display_name, is_admin, quota_bytes, disabled_at, created_at`,
		id, username, displayName, isAdmin,
	).Scan(&u.ID, &u.Username, &u.DisplayName, &u.IsAdmin, &u.QuotaBytes, &u.DisabledAt, &u.CreatedAt)

	if uniqueViolation(err) {
		return nil, ErrUserExists
	}
	if err != nil {
		return nil, fmt.Errorf("create user: %w", err)
	}
	return u, nil
}

const userCols = `id, username, display_name, is_admin, quota_bytes, disabled_at, created_at`

func scanUser(row pgx.Row) (*User, error) {
	u := &User{}
	err := row.Scan(&u.ID, &u.Username, &u.DisplayName, &u.IsAdmin, &u.QuotaBytes, &u.DisabledAt, &u.CreatedAt)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, ErrUserNotFound
	}
	if err != nil {
		return nil, err
	}
	return u, nil
}

func (s *Store) GetUserByID(ctx context.Context, id uuid.UUID) (*User, error) {
	return scanUser(s.pool.QueryRow(ctx, `SELECT `+userCols+` FROM users WHERE id = $1`, id))
}

// GetUserByUsername matches case-insensitively via the folded column.
func (s *Store) GetUserByUsername(ctx context.Context, username string) (*User, error) {
	return scanUser(s.pool.QueryRow(ctx, `SELECT `+userCols+` FROM users WHERE username_fold = lower($1)`, username))
}

func (s *Store) ListUsers(ctx context.Context) ([]*User, error) {
	rows, err := s.pool.Query(ctx, `SELECT `+userCols+` FROM users ORDER BY created_at`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var out []*User
	for rows.Next() {
		u, err := scanUser(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, u)
	}
	return out, rows.Err()
}

func (s *Store) SetUserDisabled(ctx context.Context, id uuid.UUID, disabled bool) error {
	var ts any
	if disabled {
		ts = time.Now()
	}
	tag, err := s.pool.Exec(ctx, `UPDATE users SET disabled_at = $2, updated_at = now() WHERE id = $1`, id, ts)
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return ErrUserNotFound
	}
	return nil
}

// --- credentials ------------------------------------------------------------

func (s *Store) AddCredential(ctx context.Context, userID uuid.UUID, name string, c *webauthn.Credential) error {
	transports := make([]string, 0, len(c.Transport))
	for _, t := range c.Transport {
		transports = append(transports, string(t))
	}

	_, err := s.pool.Exec(ctx, `
		INSERT INTO webauthn_credentials
			(user_id, credential_id, public_key, attestation_type, aaguid,
			 sign_count, clone_warning, transports, backup_eligible, backup_state, name)
		VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,
		userID, c.ID, c.PublicKey, c.AttestationType, c.Authenticator.AAGUID,
		int64(c.Authenticator.SignCount), c.Authenticator.CloneWarning, transports,
		c.Flags.BackupEligible, c.Flags.BackupState, name,
	)
	if uniqueViolation(err) {
		return fmt.Errorf("this passkey is already registered")
	}
	return err
}

// CredentialsForUser returns credentials in the shape go-webauthn expects.
func (s *Store) CredentialsForUser(ctx context.Context, userID uuid.UUID) ([]webauthn.Credential, error) {
	rows, err := s.pool.Query(ctx, `
		SELECT credential_id, public_key, attestation_type, aaguid, sign_count,
		       clone_warning, transports, backup_eligible, backup_state
		FROM webauthn_credentials WHERE user_id = $1`, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var out []webauthn.Credential
	for rows.Next() {
		var (
			c          webauthn.Credential
			signCount  int64
			transports []string
			backupElig bool
			backupStat bool
		)
		if err := rows.Scan(&c.ID, &c.PublicKey, &c.AttestationType, &c.Authenticator.AAGUID,
			&signCount, &c.Authenticator.CloneWarning, &transports, &backupElig, &backupStat); err != nil {
			return nil, err
		}
		c.Authenticator.SignCount = uint32(signCount)
		c.Flags.BackupEligible = backupElig
		c.Flags.BackupState = backupStat
		for _, t := range transports {
			c.Transport = append(c.Transport, protocol.AuthenticatorTransport(t))
		}
		out = append(out, c)
	}
	return out, rows.Err()
}

// ListCredentials returns display metadata for the "your passkeys" UI.
func (s *Store) ListCredentials(ctx context.Context, userID uuid.UUID) ([]*Credential, error) {
	rows, err := s.pool.Query(ctx, `
		SELECT id, user_id, credential_id, name, created_at, last_used_at
		FROM webauthn_credentials WHERE user_id = $1 ORDER BY created_at`, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var out []*Credential
	for rows.Next() {
		c := &Credential{}
		if err := rows.Scan(&c.ID, &c.UserID, &c.CredentialID, &c.Name, &c.CreatedAt, &c.LastUsedAt); err != nil {
			return nil, err
		}
		out = append(out, c)
	}
	return out, rows.Err()
}

// UpdateCredentialUsage persists the post-login sign counter. Skipping this
// would discard the clone-detection signal the counter exists to provide.
func (s *Store) UpdateCredentialUsage(ctx context.Context, credentialID []byte, signCount uint32, cloneWarning bool) error {
	_, err := s.pool.Exec(ctx, `
		UPDATE webauthn_credentials
		SET sign_count = $2, clone_warning = $3, last_used_at = now()
		WHERE credential_id = $1`, credentialID, int64(signCount), cloneWarning)
	return err
}

func (s *Store) DeleteCredential(ctx context.Context, userID, credID uuid.UUID) error {
	tag, err := s.pool.Exec(ctx,
		`DELETE FROM webauthn_credentials WHERE id = $1 AND user_id = $2`, credID, userID)
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return errors.New("credential not found")
	}
	return nil
}

// DeleteAllCredentials backs `cloudctl user reset-auth` — the lockout escape.
func (s *Store) DeleteAllCredentials(ctx context.Context, userID uuid.UUID) (int64, error) {
	tag, err := s.pool.Exec(ctx, `DELETE FROM webauthn_credentials WHERE user_id = $1`, userID)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}

// --- recovery codes ---------------------------------------------------------

// ReplaceRecoveryCodes atomically swaps a user's codes for a new set. In one
// transaction, so a failure cannot leave the account with zero usable codes.
func (s *Store) ReplaceRecoveryCodes(ctx context.Context, userID uuid.UUID, hashes []string) error {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return err
	}
	defer tx.Rollback(ctx) //nolint:errcheck // no-op once committed

	if _, err := tx.Exec(ctx, `DELETE FROM recovery_codes WHERE user_id = $1`, userID); err != nil {
		return err
	}
	for _, h := range hashes {
		if _, err := tx.Exec(ctx,
			`INSERT INTO recovery_codes (user_id, code_hash) VALUES ($1, $2)`, userID, h); err != nil {
			return err
		}
	}
	return tx.Commit(ctx)
}

// ConsumeRecoveryCode verifies a plaintext code and marks it used.
//
// It must scan every unused code because the hashes are salted — there is no
// index lookup possible. With at most 10 rows per user that is fine, and the
// argon2 cost is exactly what makes guessing expensive.
func (s *Store) ConsumeRecoveryCode(ctx context.Context, userID uuid.UUID, code string) error {
	rows, err := s.pool.Query(ctx,
		`SELECT id, code_hash FROM recovery_codes WHERE user_id = $1 AND used_at IS NULL`, userID)
	if err != nil {
		return err
	}

	type candidate struct {
		id   uuid.UUID
		hash string
	}
	var candidates []candidate
	for rows.Next() {
		var c candidate
		if err := rows.Scan(&c.id, &c.hash); err != nil {
			rows.Close()
			return err
		}
		candidates = append(candidates, c)
	}
	rows.Close()
	if err := rows.Err(); err != nil {
		return err
	}

	for _, c := range candidates {
		if !VerifyRecoveryCode(code, c.hash) {
			continue
		}
		// Conditional UPDATE: if two requests race with the same code, only one
		// affects a row, so a code cannot be redeemed twice.
		tag, err := s.pool.Exec(ctx,
			`UPDATE recovery_codes SET used_at = now() WHERE id = $1 AND used_at IS NULL`, c.id)
		if err != nil {
			return err
		}
		if tag.RowsAffected() == 0 {
			return ErrBadRecoveryCode
		}
		return nil
	}
	return ErrBadRecoveryCode
}

func (s *Store) CountUnusedRecoveryCodes(ctx context.Context, userID uuid.UUID) (int, error) {
	var n int
	err := s.pool.QueryRow(ctx,
		`SELECT count(*) FROM recovery_codes WHERE user_id = $1 AND used_at IS NULL`, userID).Scan(&n)
	return n, err
}

// --- sessions ---------------------------------------------------------------

func (s *Store) CreateSession(ctx context.Context, userID uuid.UUID, tokenHash []byte, kind, userAgent string, expiresAt time.Time) (uuid.UUID, error) {
	var id uuid.UUID
	err := s.pool.QueryRow(ctx, `
		INSERT INTO sessions (user_id, token_hash, kind, user_agent, expires_at)
		VALUES ($1,$2,$3,$4,$5) RETURNING id`,
		userID, tokenHash, kind, userAgent, expiresAt).Scan(&id)
	return id, err
}

// SessionUser resolves a token hash to its session and user in one round trip.
// The WHERE clause enforces expiry and revocation in the database rather than
// in Go, so there is no window where application logic forgets to check.
func (s *Store) SessionUser(ctx context.Context, tokenHash []byte) (*Session, *User, error) {
	sess := &Session{}
	u := &User{}
	err := s.pool.QueryRow(ctx, `
		SELECT s.id, s.user_id, s.kind, s.user_agent, s.created_at, s.last_seen_at, s.expires_at,
		       u.id, u.username, u.display_name, u.is_admin, u.quota_bytes, u.disabled_at, u.created_at
		FROM sessions s JOIN users u ON u.id = s.user_id
		WHERE s.token_hash = $1 AND s.revoked_at IS NULL AND s.expires_at > now()`,
		tokenHash,
	).Scan(&sess.ID, &sess.UserID, &sess.Kind, &sess.UserAgent, &sess.CreatedAt, &sess.LastSeenAt, &sess.ExpiresAt,
		&u.ID, &u.Username, &u.DisplayName, &u.IsAdmin, &u.QuotaBytes, &u.DisabledAt, &u.CreatedAt)

	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil, ErrSessionInvalid
	}
	if err != nil {
		return nil, nil, err
	}
	return sess, u, nil
}

func (s *Store) TouchSession(ctx context.Context, id uuid.UUID) error {
	_, err := s.pool.Exec(ctx, `UPDATE sessions SET last_seen_at = now() WHERE id = $1`, id)
	return err
}

func (s *Store) RevokeSession(ctx context.Context, userID, sessionID uuid.UUID) error {
	tag, err := s.pool.Exec(ctx,
		`UPDATE sessions SET revoked_at = now() WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL`,
		sessionID, userID)
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return ErrSessionInvalid
	}
	return nil
}

func (s *Store) RevokeSessionByTokenHash(ctx context.Context, tokenHash []byte) error {
	_, err := s.pool.Exec(ctx,
		`UPDATE sessions SET revoked_at = now() WHERE token_hash = $1`, tokenHash)
	return err
}

// RevokeAllSessions is what `cloudctl user reset-auth` uses: clearing
// credentials while leaving live sessions running would be a half-measure.
func (s *Store) RevokeAllSessions(ctx context.Context, userID uuid.UUID) (int64, error) {
	tag, err := s.pool.Exec(ctx,
		`UPDATE sessions SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL`, userID)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}

func (s *Store) ListSessions(ctx context.Context, userID uuid.UUID) ([]*Session, error) {
	rows, err := s.pool.Query(ctx, `
		SELECT id, user_id, kind, user_agent, created_at, last_seen_at, expires_at
		FROM sessions
		WHERE user_id = $1 AND revoked_at IS NULL AND expires_at > now()
		ORDER BY last_seen_at DESC`, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var out []*Session
	for rows.Next() {
		s := &Session{}
		if err := rows.Scan(&s.ID, &s.UserID, &s.Kind, &s.UserAgent, &s.CreatedAt, &s.LastSeenAt, &s.ExpiresAt); err != nil {
			return nil, err
		}
		out = append(out, s)
	}
	return out, rows.Err()
}

// --- webauthn ceremonies ----------------------------------------------------

func (s *Store) CreateCeremony(ctx context.Context, userID *uuid.UUID, kind, pendingUsername string, data *webauthn.SessionData, ttl time.Duration) (uuid.UUID, error) {
	blob, err := json.Marshal(data)
	if err != nil {
		return uuid.Nil, err
	}
	var id uuid.UUID
	err = s.pool.QueryRow(ctx, `
		INSERT INTO webauthn_ceremonies (user_id, kind, session_data, pending_username, expires_at)
		VALUES ($1,$2,$3,$4, now() + $5::interval) RETURNING id`,
		userID, kind, blob, nullString(pendingUsername), ttl.String()).Scan(&id)
	return id, err
}

// TakeCeremony fetches and deletes a ceremony in one statement.
//
// DELETE ... RETURNING makes the ceremony strictly single-use: a replayed
// finish request finds nothing, so a captured challenge cannot be reused.
func (s *Store) TakeCeremony(ctx context.Context, id uuid.UUID, kind string) (*uuid.UUID, string, *webauthn.SessionData, error) {
	var (
		userID   *uuid.UUID
		username *string
		blob     []byte
	)
	err := s.pool.QueryRow(ctx, `
		DELETE FROM webauthn_ceremonies
		WHERE id = $1 AND kind = $2 AND expires_at > now()
		RETURNING user_id, pending_username, session_data`, id, kind).Scan(&userID, &username, &blob)

	if errors.Is(err, pgx.ErrNoRows) {
		return nil, "", nil, ErrCeremonyNotFound
	}
	if err != nil {
		return nil, "", nil, err
	}

	var data webauthn.SessionData
	if err := json.Unmarshal(blob, &data); err != nil {
		return nil, "", nil, fmt.Errorf("decode ceremony: %w", err)
	}
	var name string
	if username != nil {
		name = *username
	}
	return userID, name, &data, nil
}

// Cleanup removes expired sessions and ceremonies. Called periodically; both
// tables would otherwise grow without bound.
func (s *Store) Cleanup(ctx context.Context) (sessions, ceremonies int64, err error) {
	tag, err := s.pool.Exec(ctx, `DELETE FROM sessions WHERE expires_at < now() - interval '30 days'`)
	if err != nil {
		return 0, 0, err
	}
	sessions = tag.RowsAffected()

	tag, err = s.pool.Exec(ctx, `DELETE FROM webauthn_ceremonies WHERE expires_at < now()`)
	if err != nil {
		return sessions, 0, err
	}
	return sessions, tag.RowsAffected(), nil
}

func nullString(s string) any {
	if s == "" {
		return nil
	}
	return s
}
